import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import SearchBar from "../components/SearchBar";
import { SearchContext } from "../context/Search";
import { useFetch } from "../hooks/useFetch";
import { TrendingGIF } from "../interfaces/TrendingGIF";

const Home: NextPage = () => {
  const [search, setSearch] = useState<string>("");
  const [trending, loading, error] = useFetch<TrendingGIF>(
    `https://api.giphy.com/v1/gifs/trending?api_key=${process.env.NEXT_PUBLIC_GIPHY_API_TOKEN}&limit=25&rating=r`
  );
  return (
    <div>
      <Head>
        <title>GIPHY</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-32">
        <SearchContext.Provider value={{ search, setSearch }}>
          <SearchBar />
          <div className="text-white">
            {loading && !error ? (
              <div className="font-bold">Loading...</div>
            ) : (
              <div>
                {trending?.data?.map((gif) => {
                  const { images } = gif;
                  return (
                    <img
                      src={images.fixed_height.url}
                      width={images.fixed_height.width}
                      height={images.fixed_height.height}
                    />
                  );
                })}
              </div>
            )}
          </div>
        </SearchContext.Provider>
      </div>
    </div>
  );
};

export default Home;
